name: campo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cmake
  - python=3.11
  - numpy
  - sphinx=5.3
  - sphinx-autodoc-typehints
  - pandas
  - lue>0.3.6
  - hpx=1.9.0
  - pcraster
  - xarray
  - gdal
  - networkx

