name: Build and deploy

on: [push]

jobs:

    build_and_deploy:

        runs-on: ubuntu-20.04

        name: "Build and deploy"

        steps:

        - name: checkout campo
          uses: actions/checkout@v2

        - name: configure system
          run: |
              # sudo apt-get update
              # sudo apt-get upgrade
              # sudo apt-get autoremove
              sudo apt-get --yes install lftp
        - uses: conda-incubator/setup-miniconda@v2
          with:
              activate-environment: campo-doc
              environment-file: environment/configuration/conda_environment.yaml
              python-version: 3.8
              auto-activate-base: false

        - name: build
          shell: bash -l {0}
          run: |
              mkdir build
              cd build
              cmake .. -DCAMPO_BUILD_WHEEL=ON
              make documentation
              make install
              rm -f package/dist/*gz

        - name: deploy
          env:
              ftp_server: ${{ secrets.FTP_SERVER }}
              ftp_port: ${{ secrets.FTP_PORT }}
              ftp_host: ${{ secrets.FTP_HOST }}
              ftp_username: ${{ secrets.FTP_USERNAME }}
              ftp_password: ${{ secrets.FTP_PASSWORD }}
              remote_dir1: ${{ secrets.FTP_REMOTE_DIR1 }}
              remote_dir2: ${{ secrets.FTP_REMOTE_DIR2 }}
          run: |
              cd build
              mkdir -p ~/.ssh
              echo $ftp_host >> ~/.ssh/known_hosts
              lftp -c "open --user $ftp_username --password $ftp_password -p $ftp_port $ftp_server;set sftp:auto-confirm yes;mirror --verbose --reverse --continue --parallel=2 documentation/_build/ $remote_dir1"
              lftp -c "open --user $ftp_username --password $ftp_password -p $ftp_port $ftp_server;set sftp:auto-confirm yes;mirror --verbose --reverse --continue package/dist/ $remote_dir2"
